name = "PastaQ"
uuid = "30b07047-aa8b-4c78-a4e8-24d720215c19"
authors = ["Giacomo Torlai <gttorlai@amazon.com>", "Matthew Fishman <mfishman@flatironinstitute.org>"]
version = "0.0.14"

[deps]
Convex = "f65535da-76fb-5f13-bab9-19810c17039a"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
ITensors = "9136182c-28ba-11e9-034c-db9fb085ebd5"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Observers = "338f10d5-c7f1-4033-a7d1-f9dec39bcaa0"
Optimisers = "3bd65402-5787-11e9-1adc-39752487f4e2"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SCS = "c946c3f1-0d1f-5ce8-9dea-7daa1f7e2d13"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
TupleTools = "9d95972d-f1c8-5527-a6e0-b4b365fa01f6"

[compat]
Convex = "0.14.16"
HDF5 = "0.13.1, 0.14, 0.15"
ITensors = "0.1.41, 0.2"
JLD2 = "0.4.14"
Observers = "0.0.3"
Optimisers = "0.1.0"
SCS = "0.7.1"
StatsBase = "0.33"
TupleTools = "1.3.0"
julia = "1.6"
